on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: false
        
      - uses: actions/checkout@v3
  
      - name: Build
        run: go build -v ./...
  
      - name: Test
        run: go test -v ./...
